# Generated by Django 5.1.5 on 2025-01-25 15:05

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='EcoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('image', models.ImageField(upload_to='images/ecoblog', verbose_name='Imagen')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección')),
                ('description', tinymce.models.HTMLField(verbose_name='Descripción')),
                ('flora', tinymce.models.HTMLField(verbose_name='Flora')),
                ('fauna', tinymce.models.HTMLField(verbose_name='Fauna')),
                ('activities', tinymce.models.HTMLField(verbose_name='Actividades')),
                ('established_date', models.DateField(blank=True, null=True, verbose_name='Fecha Establecido')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecoblog.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'ecosite',
                'verbose_name_plural': 'ecosites',
            },
        ),
    ]
