# Generated by Django 5.1.5 on 2025-01-25 15:13

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecosite',
            name='activities',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Actividades'),
        ),
        migrations.AlterField(
            model_name='ecosite',
            name='established_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha establecido'),
        ),
        migrations.AlterField(
            model_name='ecosite',
            name='fauna',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Fauna'),
        ),
        migrations.AlterField(
            model_name='ecosite',
            name='flora',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Flora'),
        ),
    ]
