# Generated by Django 5.1.5 on 2025-01-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoblog', '0002_alter_ecosite_activities_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EcoSite',
            new_name='ProtectedArea',
        ),
    ]
